apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  app.properties: |
    runmode=dist
    namespace={{ .Release.Namespace }}
    app.image={{ .Values.app.image.name }}:{{ .Values.app.image.tag }}
    app.logging={{ .Values.app.logging }}
    app.tracing={{ .Values.app.tracing }}
    illusionist.approach={{ .Values.illusionist.approach }}
    illusionist.url=https://illusionist-preview.flowstorm.ai

