apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  app.properties: |
    runmode=dist
    namespace={{ .Release.Namespace }}
    app.image={{ .Values.app.image.name }}:{{ .Values.app.image.tag }}
    app.logging={{ .Values.app.logging }}
    app.tracing={{ .Values.app.tracing }}
    sender.from.email={{ .Values.sender.from.email }}
    sender.from.name={{ .Values.sender.from.name }}
    jwtauth.issuer={{ .Values.jwtauth.issuer }}
    jwtauth.verify={{ .Values.jwtauth.verify }}
    illusionist.url=https://illusionist-preview.flowstorm.ai
